version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge