name: CI and CD

on:
  push:
    branches: 
      - main
      - pho_cdci
      - master

env:
  REGISTRY: "docker.io"
  IMAGE_NAME: "phoebusyip/plant5_message_board"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Build container image
        run: docker build -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login $REGISTRY -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    
      - name: Push image to Docker Hub
        run: docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        run: |
          sshpass -p ${{ secrets.DROPLET_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} << 'ENDSSH'
          cd /root/myapp  # Replace with the path to your app on the Droplet
          git pull
          docker-compose down -v
          docker-compose build --no-cache
          docker-compose up -d
          ENDSSH