name: Deploy to DigitalOcean

on:
  push:
    branches:
      - deploy2  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        run: |
          sshpass -p ${{ secrets.DROPLET_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} << 'ENDSSH'
          cd /root/myapp  # Replace with the path to your app on the Droplet
          git pull
          docker-compose down -v
          docker-compose build --no-cache
          docker-compose up -d
          ENDSSH
# jeros jreigjes